export const data = [
    { label: 'Cuidado de niños', value: 'Cuidado de niños' },
    { label: 'Cuidado de personas mayores', value: 'Cuidado de personas mayores' },
    { label: 'Limpieza de hogar', value: 'Limpieza de hogar' },
    { label: 'Cocina y preparación de comidas', value: 'Cocina y preparación de comidas' },
    { label: 'Reparación de electrodomésticos', value: 'Reparación de electrodomésticos' },
    { label: 'Reparación de computadoras', value: 'Reparación de computadoras' },
    { label: 'Diseño gráfico', value: 'Diseño gráfico' },
    { label: 'Desarrollo web', value: 'Desarrollo web' },
    { label: 'Desarrollo de aplicaciones móviles', value: 'Desarrollo de aplicaciones móviles' },
    { label: 'Clases particulares', value: 'Clases particulares' },
    { label: 'Entrenamiento personal', value: 'Entrenamiento personal' },
    { label: 'Diseño de interiores', value: 'Diseño de interiores' },
    { label: 'Plomería', value: 'Plomería' },
    { label: 'Electricidad', value: 'Electricidad' },
    { label: 'Carpintería', value: 'Carpintería' },
    { label: 'Jardinería', value: 'Jardinería' },
    { label: 'Pintura', value: 'Pintura' },
    { label: 'Reparación de autos', value: 'Reparación de autos' },
    { label: 'Cuidado de mascotas', value: 'Cuidado de mascotas' },
    { label: 'Servicio de mudanza', value: 'Servicio de mudanza' },
    { label: 'Fotografía', value: 'Fotografía' },
    { label: 'Filmación y edición de videos', value: 'Filmación y edición de videos' },
    { label: 'Organización de eventos', value: 'Organización de eventos' },
    { label: 'Maquillaje y peinado', value: 'Maquillaje y peinado' },
    { label: 'Corte y costura', value: 'Corte y costura' },
    { label: 'Traducción de documentos', value: 'Traducción de documentos' },
    { label: 'Asesoramiento legal', value: 'Asesoramiento legal' },
    { label: 'Asesoramiento financiero', value: 'Asesoramiento financiero' },
    { label: 'Asesoramiento en seguros', value: 'Asesoramiento en seguros' },
    { label: 'Asesoramiento en inversiones', value: 'Asesoramiento en inversiones' },
    { label: 'Servicio de limusina', value: 'Servicio de limusina' },
    { label: 'Alquiler de trajes y vestidos', value: 'Alquiler de trajes y vestidos' },
    { label: 'Servicio de reparación de calzado', value: 'Servicio de reparación de calzado' },
    { label: 'Servicio de lavandería', value: 'Servicio de lavandería' },
    { label: 'Alquiler de herramientas', value: 'Alquiler de herramientas' },
    { label: 'Entrega de compras', value: 'Entrega de compras' },
    { label: 'Transporte escolar', value: 'Transporte escolar' },
    { label: 'Lavado de autos', value: 'Lavado de autos' },
    { label: 'Guardería para mascotas', value: 'Guardería para mascotas' },
    { label: 'Alquiler de bicicletas', value: 'Alquiler de bicicletas' },
    { label: 'Reparación de ropa', value: 'Reparación de ropa' },
    { label: 'Mantenimiento de piscinas', value: 'Mantenimiento de piscinas' },
    { label: 'Instalación de alarmas', value: 'Instalación de alarmas' },
    { label: 'Reparación de techos', value: 'Reparación de techos' },
    { label: 'Instalación de aire acondicionado', value: 'Instalación de aire acondicionado' },
    { label: 'Reparación de celulares', value: 'Reparación de celulares' },
    { label: 'Reparación de calefón', value: 'Reparación de calefón' },
    { label: 'Instalación de paneles solares', value: 'Instalación de paneles solares' },
    { label: 'Reparación de puertas', value: 'Reparación de puertas' },
    { label: 'Instalación de cámaras de seguridad', value: 'Instalación de cámaras de seguridad' },
    { label: 'Reparación de ventanas', value: 'Reparación de ventanas' },
    { label: 'Instalación de pisos', value: 'Instalación de pisos' },
    { label: 'Reparación de grifos', value: 'Reparación de grifos' },
    { label: 'Instalación de puertas de garaje', value: 'Instalación de puertas de garaje' },
    { label: 'Reparación de paredes', value: 'Reparación de paredes' },
    { label: 'Instalación de sistemas de riego', value: 'Instalación de sistemas de riego' },
    { label: 'Reparación de lavarropas y secarropas', value: 'Reparación de lavarropas y secarropas' },
    { label: 'Instalación de sistemas de iluminación', value: 'Instalación de sistemas de iluminación' },
    { label: 'Reparación de hornos y estufas', value: 'Reparación de hornos y estufas' },
    { label: 'Instalación de sistemas de sonido', value: 'Instalación de sistemas de sonido' },
    { label: 'Reparación de refrigeradores', value: 'Reparación de refrigeradores' },
    { label: 'Instalación de sistemas de climatización', value: 'Instalación de sistemas de climatización' },
    { label: 'Reparación de equipos de audio y video', value: 'Reparación de equipos de audio y video' },
    { label: 'Instalación de sistemas de domótica', value: 'Instalación de sistemas de domótica' },
    { label: 'Reparación de equipos de oficina', value: 'Reparación de equipos de oficina' },
    { label: 'Instalación de sistemas de rastreo vehicular', value: 'Instalación de sistemas de rastreo vehicular' },
    { label: 'Reparación de equipos de sonido profesional', value: 'Reparación de equipos de sonido profesional' },
    { label: 'Instalación de sistemas de comunicación', value: 'Instalación de sistemas de comunicación' },
    { label: 'Reparación de consolas de videojuegos', value: 'Reparación de consolas de videojuegos' },
    { label: 'Instalación de sistemas de videovigilancia', value: 'Instalación de sistemas de videovigilancia' },
    { label: 'Reparación de equipos de fotografía', value: 'Reparación de equipos de fotografía' },
    { label: 'Instalación de sistemas de energía solar', value: 'Instalación de sistemas de energía solar' },
    { label: 'Reparación de equipos de impresión', value: 'Reparación de equipos de impresión' },
    { label: 'Instalación de sistemas de acceso remoto', value: 'Instalación de sistemas de acceso remoto' },
    { label: 'Reparación de equipos de telecomunicaciones', value: 'Reparación de equipos de telecomunicaciones' },
    { label: 'Instalación de sistemas de control de acceso', value: 'Instalación de sistemas de control de acceso' },
    { label: 'Reparación de equipos de audio para automóviles', value: 'Reparación de equipos de audio para automóviles' },
    { label: 'Instalación de sistemas de navegación GPS', value: 'Instalación de sistemas de navegación GPS' },
    { label: 'Reparación de equipos de iluminación para automóviles', value: 'Reparación de equipos de iluminación para automóviles' },
    { label: 'Instalación de sistemas de seguridad para automóviles', value: 'Instalación de sistemas de seguridad para automóviles' },
    { label: 'Reparación de equipos de navegación para automóviles', value: 'Reparación de equipos de navegación para automóviles' },
    { label: 'Instalación de sistemas de iluminación para motocicletas', value: 'Instalación de sistemas de iluminación para motocicletas' },
    { label: 'Instalación de sistemas de seguridad para motocicletas', value: 'Instalación de sistemas de seguridad para motocicletas' },
    { label: 'Reparación y mantenimiento de bicicletas', value: 'Reparación y mantenimiento de bicicletas' },
    { label: 'Albañileria', value: 'Albañileria' },
    { label: 'Plomeria', value: 'Plomeria' },
    { label: 'Mecánica', value: 'Mecánica' },
    { label: 'Peluqueria', value: 'Peluqueria' },
    { label: 'Profesor particular', value: 'Profesor particular' },
    { label: 'Apoyo escolar', value: 'Apoyo escolar' },
    { label: 'Psicología', value: 'Psicología' },
    { label: 'Quiropraxia', value: 'Quiropraxia' },
    { label: 'Kinesiología', value: 'Kinesiología' },
    { label: 'Masajes', value: 'Masajes' },
    { label: 'Cadete', value: 'Cadete' },
    { label: 'Delivery', value: 'Delivery' },
    { label: 'Alquiler de sillas y mesas', value: 'Alquiler de sillas y mesas' },
    { label: 'Alquiler de vajillas', value: 'Alquiler de vajillas' },
    { label: 'Alquiler de salón de fiestas', value: 'Alquiler de salón de fiestas' },
    { label: 'Alquiler de canchas', value: 'Alquiler de canchas' },
    { label: 'Cajero', value: 'Cajero' },
    { label: 'Community manager', value: 'Community manager' },
    { label: 'Animacion de fiesta', value: 'Animacion de fiesta' },
    { label: 'DJ', value: 'DJ' },
    { label: 'Pastelería', value: 'Pastelería' },
    { label: 'Mesero', value: 'Mesero' },
    { label: 'Preparación física', value: 'Preparación física' },
    { label: 'Obstetra', value: 'Obstetra' },
    { label: 'Maestro mayor de obra', value: 'Maestro mayor de obra' },
    { label: 'Durlero', value: 'Durlero' },
    { label: 'Administrativo', value: 'Administrativo' },
    { label: 'Seguridad', value: 'Seguridad' },
    { label: 'Decorador de eventos', value: 'Decorador de eventos' },
    { label: 'Medicina', value: 'Medicina' },
    { label: 'Músico', value: 'Músico' },
    { label: 'Odontología', value: 'Odontología' },
    { label: 'Prensa y ceremonial', value: 'Prensa y ceremonial' },
    { label: 'Oculista', value: 'Oculista' },
    { label: 'Cardiología', value: 'Cardiología' },
    { label: 'Otorrinolaringólogo', value: 'Otorrinolaringólogo' },
    { label: 'Pediatría', value: 'Pediatría' },
    { label: 'Clínico', value: 'Clínico' },
    { label: 'Neurología', value: 'Neurología' },
    { label: 'Cirujano', value: 'Cirujano' },
    { label: 'Cirujano plástico', value: 'Cirujano plástico' },
    { label: 'Traumatología', value: 'Traumatología' },
    { label: 'Urología ', value: 'Urología ' },
    { label: 'Estadística', value: 'Estadística' },
    { label: 'Radiología', value: 'Radiología' },
    { label: 'Ecografista ', value: 'Ecografista ' },
    { label: 'Psiquiatra', value: 'Psiquiatra' },
    { label: 'Administración de empresas', value: 'Administración de empresas' },
    { label: 'Mecánica dental', value: 'Mecánica dental' },
    { label: 'Instrumentista', value: 'Instrumentista' },
    { label: 'Anestesista', value: 'Anestesista' },
    { label: 'Cosmetólogia', value: 'Cosmetólogia' },
    { label: 'Gasista', value: 'Gasista' },
    { label: 'Soldador', value: 'Soldador' },
    { label: 'Gestor', value: 'Gestor' },
    { label: 'Agricultura', value: 'Agricultura' },
    { label: 'Paisajismo', value: 'Paisajismo' },
    { label: 'Escritor', value: 'Escritor' },
    { label: 'Guardavida', value: 'Guardavida' },
    { label: 'Panadero', value: 'Panadero' },
    { label: 'Rescatista', value: 'Rescatista' },
    { label: 'Adiestramiento', value: 'Adiestramiento' },
    { label: 'Morguero', value: 'Morguero' },
    { label: 'Corredor de bolsa', value: 'Corredor de bolsa' },
    { label: 'Ingeniería', value: 'Ingeniería' },
    { label: 'Arquitectura', value: 'Arquitectura' },
    { label: 'Abogacía', value: 'Abogacía' },
    { label: 'Contaduría', value: 'Contaduría' },
    { label: 'Economista', value: 'Economista' },
    { label: 'Azafata', value: 'Azafata' },
    { label: 'Piloto de avión', value: 'Piloto de avión' },
    { label: 'Actor de doblaje', value: 'Actor de doblaje' },
    { label: 'Enfermería', value: 'Enfermería' },
    { label: 'Caddie', value: 'Caddie' },
    { label: 'Bachero', value: 'Bachero' },
    { label: 'Patissier', value: 'Patissier' },
    { label: 'Parrillero', value: 'Parrillero' },
    { label: 'Recepcionista', value: 'Recepcionista' },
    { label: 'Mucama', value: 'Mucama' },
    { label: 'Sereno', value: 'Sereno' },
    { label: 'Farmacéutica', value: 'Farmacéutica' },
    { label: 'Veterinaria', value: 'Veterinaria' },
    { label: 'Producción de vídeo', value: 'Producción de vídeo' },
    { label: 'Produccion de musica', value: 'Produccion de musica' },
    { label: 'Producción de cine', value: 'Producción de cine' },
    { label: 'Actuación', value: 'Actuación' },
    { label: 'Guía', value: 'Guía' },
    { label: 'Bailarín', value: 'Bailarín' },
    { label: 'Carnicería', value: 'Carnicería' },
    { label: 'Guionista', value: 'Guionista' },
    { label: 'Otro', value: 'Otro' }
];